FROM python:3.12-slim-bookworm

ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1
ENV TEMP_DIR=/tmp/vine-and-fig

RUN apt-get -qq update && \
    apt-get -qq install --yes --no-install-recommends \
      ca-certificates \
      libgl1 \
      libglx-mesa0 \
      libglu1-mesa \
      libxrender1 \
      libsm6 \
      libice6 \
      libxext6 > /dev/null && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-cli.txt .

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-cli.txt

COPY src /app/src

ENTRYPOINT ["python", "-m", "app.cli"]
CMD ["--help"]
